server:
  port: 8082

spring:
  application:
    name: RATE-AGGREGATION-SERVICE
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/rates_aggregator?useSSL=false&serverTimezone=UTC
    username: root
    password: password123
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# Markup percent: 0.1% default -> 0.01
rates:
  markup: 0.01
  cache-ttl-seconds: 30

app:
  scheduling:
    rate-fetch-interval-ms: 120000  # Default: 1 hour (in milliseconds)
  api:
    exchange-rate:
      key: b5a2352c9114294cba5251e8
      url: https://v6.exchangerate-api.com
    forex-rate:
      key: d5696d818464c1bf3f668516e54e1a58
      url: https://api.forexrateapi.com
    free-currency:
      key: fca_live_hPiAOXn2Sqosa9Ks9S5ZjO8U6A10ctjNLle3vkF1
      url: https://api.freecurrencyapi.com

jwt:
  secret: ThisIsASecureSecretKeyWithAtLeast32CharactersLong123!
  expiration:
    ms: 86400000