server:
  port: 9191

spring:
  application:
    name: API-GATEWAY-
  cloud:
    config:
      import-check:
        enabled: false
    gateway:
      routes:
        - id: AUTHENTICATION-SERVICE
          uri: lb//AUTHENTICATION-SERVICE
          predicates:
            - Path=//api/auth/**
          filters:
            - name: CircuitBreaker
              args: AUTHENTICATION-SERVICE
              fallbackUri: forward:/auth-service-fallback

        - id: RATE-AGGREGATION-SERVICE
          uri: lb//RATE-AGGREGATION-SERVICE
          predicates:
            - Path=/api/rates/**
          filters:
            - name: CircuitBreaker
              args: RATE-AGGREGATION-SERVICE
              fallbackUri: forward:/currency-service-fallback

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000


